export type MessageRole = "system" | "user" | "assistant" | "tool";

export interface Message {
	role: MessageRole;
	content: string;
	toolCallId?: string;
	toolCalls?: ToolCall[];
}

export interface ToolCall {
	id: string;
	name: string;
	arguments: Record<string, unknown>;
}

export interface ToolResult {
	toolCallId: string;
	content: string;
	isError?: boolean;
}

export interface ToolDefinition {
	name: string;
	description: string;
	parameters: Record<string, unknown>;
}

export interface ChatOptions {
	model: string;
	messages: Message[];
	tools?: ToolDefinition[];
	temperature?: number;
	maxTokens?: number;
	thinking?: {
		enabled?: boolean;
		effort?: "none" | "low" | "medium" | "high";
		budgetTokens?: number;
	};
	signal?: AbortSignal;
	/**
	 * Maximum number of chunks to yield before pausing (backpressure safety)
	 * Prevents memory exhaustion on very large responses.
	 * Default: 10000 chunks (approximately 10MB of text)
	 */
	maxChunks?: number;
}

/**
 * Normalized token usage reported by the provider. Every field is optional
 * because not every provider reports every metric; callers must treat missing
 * values as "unavailable" rather than zero.
 */
export interface TokenUsage {
	/** Prompt / input tokens sent to the model. */
	inputTokens?: number;
	/** Completion / output tokens generated by the model. */
	outputTokens?: number;
	/** Total tokens (input + output) when the provider reports it. */
	totalTokens?: number;
	/** Cached prompt tokens (prompt-caching hits), when available. */
	cachedTokens?: number;
	/** Reasoning / thinking tokens, when available. */
	reasoningTokens?: number;
}

export interface ChatResponse {
	content: string;
	toolCalls?: ToolCall[];
	finishReason: "stop" | "tool_calls" | "length" | "error";
	/** Token usage for this call, when the provider returns it. */
	usage?: TokenUsage;
}

export interface StreamChunk {
	content?: string;
	toolCalls?: ToolCall[];
	done: boolean;
	/** Token usage, emitted on the final chunk when the provider returns it. */
	usage?: TokenUsage;
}

import type { ModelCapabilities } from "./capabilities.js";

export interface LLMClient {
	chat(options: ChatOptions): Promise<ChatResponse>;
	stream(options: ChatOptions): AsyncGenerator<StreamChunk, void, unknown>;
	getCapabilities(model: string): Promise<ModelCapabilities>;
}
