/**
 * Normalized token usage.
 *
 * Different LLM providers report token usage under different field names
 * (prompt_tokens vs input_tokens, completion_tokens vs output_tokens, etc.).
 * This module defines a single internal shape and maps each provider's raw
 * usage object into it.
 */

/**
 * Normalized token usage. Every field is optional because not every provider
 * reports every metric; callers must treat missing values as "unavailable"
 * rather than zero.
 */
export interface TokenUsage {
	/** Prompt / input tokens sent to the model. */
	inputTokens?: number;
	/** Completion / output tokens generated by the model. */
	outputTokens?: number;
	/** Total tokens (input + output) when the provider reports it. */
	totalTokens?: number;
	/** Cached prompt tokens (prompt-caching hits), when available. */
	cachedTokens?: number;
	/** Reasoning / thinking tokens, when available. */
	reasoningTokens?: number;
}

/** A sentinel meaning "the provider returned no usage data". */
export const NO_USAGE: Readonly<TokenUsage> = Object.freeze({});

/** True when a usage object carries no usable metric. */
export function isUsageUnavailable(usage: TokenUsage | undefined): boolean {
	if (!usage) return true;
	return (
		usage.inputTokens === undefined &&
		usage.outputTokens === undefined &&
		usage.totalTokens === undefined &&
		usage.cachedTokens === undefined &&
		usage.reasoningTokens === undefined
	);
}

/** Sum two usage objects, treating undefined as "not present" (not zero). */
export function mergeUsage(a: TokenUsage | undefined, b: TokenUsage | undefined): TokenUsage {
	const result: TokenUsage = {};
	const add = (k: keyof TokenUsage): void => {
		const av = a?.[k];
		const bv = b?.[k];
		if (av !== undefined || bv !== undefined) {
			(result[k] as number | undefined) = (av ?? 0) + (bv ?? 0);
		}
	};
	add("inputTokens");
	add("outputTokens");
	add("totalTokens");
	add("cachedTokens");
	add("reasoningTokens");
	// Recompute total from parts when both parts are known but total was not.
	if (result.totalTokens === undefined && result.inputTokens !== undefined && result.outputTokens !== undefined) {
		result.totalTokens = result.inputTokens + result.outputTokens;
	}
	return result;
}

/**
 * Map an OpenAI-style usage object into the normalized shape.
 * OpenAI reports: prompt_tokens, completion_tokens, total_tokens, and
 * prompt_tokens_details.cached_tokens / completion_tokens_details.reasoning_tokens.
 */
export function fromOpenAIUsage(raw: Record<string, unknown> | undefined): TokenUsage {
	if (!raw) return NO_USAGE;
	const num = (v: unknown): number | undefined => (typeof v === "number" && Number.isFinite(v) ? v : undefined);
	const promptDetails = raw.prompt_tokens_details as Record<string, unknown> | undefined;
	const completionDetails = raw.completion_tokens_details as Record<string, unknown> | undefined;
	return {
		inputTokens: num(raw.prompt_tokens) ?? num(raw.input_tokens),
		outputTokens: num(raw.completion_tokens) ?? num(raw.output_tokens),
		totalTokens: num(raw.total_tokens),
		cachedTokens: num(promptDetails?.cached_tokens),
		reasoningTokens: num(completionDetails?.reasoning_tokens),
	};
}

/**
 * Map an Anthropic-style usage object into the normalized shape.
 * Anthropic reports: input_tokens, output_tokens, cache_read_input_tokens /
 * cache_creation_input_tokens, and (on some models) reasoning tokens.
 */
export function fromAnthropicUsage(raw: Record<string, unknown> | undefined): TokenUsage {
	if (!raw) return NO_USAGE;
	const num = (v: unknown): number | undefined => (typeof v === "number" && Number.isFinite(v) ? v : undefined);
	const cachedRead = num(raw.cache_read_input_tokens) ?? 0;
	const cachedCreate = num(raw.cache_creation_input_tokens) ?? 0;
	const cached = cachedRead + cachedCreate;
	return {
		inputTokens: num(raw.input_tokens),
		outputTokens: num(raw.output_tokens),
		// Anthropic does not report a total; derive it from input + output.
		totalTokens:
			num(raw.input_tokens) !== undefined && num(raw.output_tokens) !== undefined
				? (num(raw.input_tokens) ?? 0) + (num(raw.output_tokens) ?? 0)
				: undefined,
		cachedTokens: cached > 0 ? cached : undefined,
		reasoningTokens: num(raw.reasoning_tokens),
	};
}

/**
 * Map an Ollama-style usage object into the normalized shape.
 * Ollama reports: prompt_eval_count, eval_count, and (optionally)
 * prompt_eval_count details for cached prompt tokens.
 */
export function fromOllamaUsage(raw: Record<string, unknown> | undefined): TokenUsage {
	if (!raw) return NO_USAGE;
	const num = (v: unknown): number | undefined => (typeof v === "number" && Number.isFinite(v) ? v : undefined);
	const input = num(raw.prompt_eval_count);
	const output = num(raw.eval_count);
	return {
		inputTokens: input,
		outputTokens: output,
		totalTokens: input !== undefined && output !== undefined ? input + output : undefined,
	};
}

/**
 * Generic fallback: try to coerce an unknown usage object by sniffing for the
 * common field names. Used when the provider shape is not known ahead of time.
 */
export function fromUnknownUsage(raw: Record<string, unknown> | undefined): TokenUsage {
	if (!raw) return NO_USAGE;
	const openai = fromOpenAIUsage(raw);
	if (!isUsageUnavailable(openai)) return openai;
	const anthropic = fromAnthropicUsage(raw);
	if (!isUsageUnavailable(anthropic)) return anthropic;
	const ollama = fromOllamaUsage(raw);
	if (!isUsageUnavailable(ollama)) return ollama;
	return NO_USAGE;
}
