import * as fs from "node:fs/promises";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const packageJsonPath = path.resolve(__dirname, "../package.json");
const outputFile = path.resolve(__dirname, "../src/utils/version-constant.ts");

async function generate() {
	const packageJson = JSON.parse(await fs.readFile(packageJsonPath, "utf-8"));
	const version = packageJson.version;

	const output = `// Auto-generated by scripts/generate-version.ts
// DO NOT EDIT - run "bun run generate:version" to regenerate

export const VERSION = "${version}";
`;

	await fs.writeFile(outputFile, output);
	console.log(`Generated ${outputFile} with version ${version}`);
}

generate().catch(console.error);
