import * as fs from "node:fs/promises";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const skillsDir = path.resolve(__dirname, "../src/skills/builtin");
const outputFile = path.resolve(__dirname, "../src/skills/embedded-content.ts");

async function generate() {
  const entries = await fs.readdir(skillsDir, { withFileTypes: true });
  const skills: { name: string; content: string }[] = [];

  for (const entry of entries) {
    if (entry.isDirectory()) {
      const skillPath = path.join(skillsDir, entry.name, "SKILL.md");
      try {
        const content = await fs.readFile(skillPath, "utf-8");
        skills.push({ name: entry.name, content });
      } catch {
        // Skip skills without SKILL.md
      }
    }
  }

  const output = `// Auto-generated by scripts/generate-embedded-skills.ts
// DO NOT EDIT - run "bun run generate:skills" to regenerate

export const EMBEDDED_SKILL_CONTENT: Record<string, string> = {
${skills.map((s) => `  "${s.name}": ${JSON.stringify(s.content)}`).join(",\n")}
};
`;

  await fs.writeFile(outputFile, output);
  console.log(`Generated ${outputFile} with ${skills.length} skills`);
}

generate().catch(console.error);
